### ISSUE TITLE
PermissionError: [WinError 5] Access is denied

### ISSUE THREAD

**Issue by xd003** [kjtsune/embyToLocalPlayer#23]
Hello, thanks for making this wonderful tool. This is the very first time i am using this tool.  i am getting the following error when i play any file in emby website while running `embyToLocalPlayer_debug.bat` as admin

```
[12/20/23 20:00:23] ['Python path: C:\\Users\\_hide_user_\\AppData\\Local\\Programs\\Python\\Python312\\python.exe']
[12/20/23 20:00:23] ['ini path: C:\\Users\\_hide_user_\\Downloads\\embyToLocalPlayer\\embyToLocalPlayer_config.ini']
[12/20/23 20:00:23] Windows-11-10.0.22631-SP0 Python-3.12.0
[12/20/23 20:00:26] C:\Users\_hide_user_\Downloads\embyToLocalPlayer\embyToLocalPlayer.py
[12/20/23 20:00:26] serving at 127.0.0.1:58000
127.0.0.1 - - [20/Dec/2023 20:01:14] "POST /embyToLocalPlayer/ HTTP/1.1" 200 -
[12/20/23 20:01:14] server=emby mount_disk_mode=False
[12/20/23 20:01:14] ['emby.xd_mix_host_ not match: gui[except_host] []']
[12/20/23 20:01:14] command line: ['"C:\\Program Files\\mpv\\mpv.exe"', 'https://emby.xd_mix_host_/emby/videos/962/original.mkv?DeviceId=a4e7280e-6df0-4a47-867d-9a725e3da5cf&MediaSourceId=1db25df025b26dfaea14ea236e6cca43&PlaySessionId=94ccee27af7c47439bd9fed593e44780&api_key=_hide_api_key_&Static=true']
[12/20/23 20:01:14] ["emby.xd_mix_host_ match: playlist[enable_host] ['localhost', '127.0.0.1', '192.168.', '192-168-', 'example.com:8096', '.']"]
[12/20/23 20:01:14] ['"C:\\Program Files\\mpv\\mpv.exe"', 'https://emby.xd_mix_host_/emby/videos/962/original.mkv?DeviceId=a4e7280e-6df0-4a47-867d-9a725e3da5cf&MediaSourceId=1db25df025b26dfaea14ea236e6cca43&PlaySessionId=94ccee27af7c47439bd9fed593e44780&api_key=_hide_api_key_&Static=true', '--force-media-title=The Godfather (1972)  |  The Godfather (1972) - HD Version [BluRay-1080p][10bit][x265][AC3 5.1][HI+EN]-afm72[tmdbid-238].mkv', '--osd-playing-msg=The Godfather (1972)  |  The Godfather (1972) - HD Version [BluRay-1080p][10bit][x265][AC3 5.1][HI+EN]-afm72[tmdbid-238].mkv', '--start=0', '--input-ipc-server=\\\\.\\pipe\\pipe_nameA', '--script-opts-append=autoload-disabled=yes', '--fullscreen=yes']
Exception in thread Thread-4 (start_play):
Traceback (most recent call last):
  File "C:\Users\_hide_user_\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "C:\Users\_hide_user_\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\_hide_user_\Downloads\embyToLocalPlayer\embyToLocalPlayer.py", line 100, in start_play
    player_manager.start_player(cmd=cmd, start_sec=start_sec, sub_file=sub_file, media_title=media_title,
  File "C:\Users\_hide_user_\Downloads\embyToLocalPlayer\utils\players.py", line 45, in start_player
    self.player_kwargs = player_start_func_dict[self.player_name](**kwargs)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\_hide_user_\Downloads\embyToLocalPlayer\utils\players.py", line 227, in mpv_player_start
    player = subprocess.Popen(cmd, env=os.environ)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\_hide_user_\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\_hide_user_\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied
Traceback (most recent call last):
  File "C:\Users\_hide_user_\Downloads\embyToLocalPlayer\embyToLocalPlayer.py", line 161, in <module>
    run_server(_RequestHandler)
  File "C:\Users\_hide_user_\Downloads\embyToLocalPlayer\utils\net_tools.py", line 29, in run_server
    httpd.serve_forever()
  File "C:\Users\_hide_user_\AppData\Local\Programs\Python\Python312\Lib\socketserver.py", line 235, in serve_forever
    ready = selector.select(poll_interval)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\_hide_user_\AppData\Local\Programs\Python\Python312\Lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\_hide_user_\AppData\Local\Programs\Python\Python312\Lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by kjtsune** [comment]
不要使用管理员运行脚本。
下载最新mpv保存到其他目录测试。https://sourceforge.net/projects/mpv-player-windows/files/64bit/
更换其他播放器测试，比如mpv.net。

Do not run the `embyToLocalPlayer_debug.bat` as an administrator.
https://sourceforge.net/projects/mpv-player-windows/files/64bit/
Download the latest version of mpv and save it to a different directory for testing. eg:Downloads 
Use another player for testing, such as mpv.net.

**Comment by xd003** [comment]
> 不要使用管理员运行脚本。 下载最新mpv保存到其他目录测试。https://sourceforge.net/projects/mpv-player-windows/files/64bit/ 更换其他播放器测试，比如mpv.net。
> 
> Do not run the `embyToLocalPlayer_debug.bat` as an administrator. https://sourceforge.net/projects/mpv-player-windows/files/64bit/ Download the latest version of mpv and save it to a different directory for testing. eg:Downloads Use another player for testing, such as mpv.net.

Thanks for the input, i just copied my mpv folder from `C:\Program Files` to `Downloads` folder, i no longer get the error `PermissionError: [WinError 5] Access is denied` but when i click on play button in emby, mpv doesn't seem to open for some reason

```
[12/21/23 08:06:40] ['Python path: C:\\Users\\_hide_user_\\AppData\\Local\\Programs\\Python\\Python312\\python.exe']
[12/21/23 08:06:40] ['ini path: C:\\Users\\_hide_user_\\Downloads\\embyToLocalPlayer\\embyToLocalPlayer_config.ini']
[12/21/23 08:06:40] Windows-11-10.0.22631-SP0 Python-3.12.0
[12/21/23 08:06:42] C:\Users\_hide_user_\Downloads\embyToLocalPlayer\embyToLocalPlayer.py
[12/21/23 08:06:42] serving at 127.0.0.1:58000
127.0.0.1 - - [21/Dec/2023 08:06:46] "POST /embyToLocalPlayer/ HTTP/1.1" 200 -
[12/21/23 08:06:46] server=emby mount_disk_mode=False
[12/21/23 08:06:46] ['emby.xd_mix_host_ not match: gui[except_host] []']
[12/21/23 08:06:46] command line: ['C:\\Users\\_hide_user_\\Downloads\\mpv-x86_64-20231210-git-443c248\\mpv.exe', 'https://emby.xd_mix_host_/emby/videos/373/original.mkv?DeviceId=a4e7280e-6df0-4a47-867d-9a725e3da5cf&MediaSourceId=7eeeadab38ea5b51f46fa5353f5ade31&PlaySessionId=dd7c50efe6e3433ab1eb3b0f468d0500&api_key=_hide_api_key_&Static=true']
[12/21/23 08:06:46] ["emby.xd_mix_host_ match: playlist[enable_host] ['localhost', '127.0.0.1', '192.168.', '192-168-', 'example.com:8096', '.']"]
[12/21/23 08:06:46] ['C:\\Users\\_hide_user_\\Downloads\\mpv-x86_64-20231210-git-443c248\\mpv.exe', 'https://emby.xd_mix_host_/emby/videos/373/original.mkv?DeviceId=a4e7280e-6df0-4a47-867d-9a725e3da5cf&MediaSourceId=7eeeadab38ea5b51f46fa5353f5ade31&PlaySessionId=dd7c50efe6e3433ab1eb3b0f468d0500&api_key=_hide_api_key_&Static=true', '--force-media-title=Fukrey 3 (2023)  |  Fukrey 3 (2023) - HD Version [WEBDL-1080p][8bit][AVC][EAC3 5.1][HI]-TELLY[tmdbid-805785].mkv', '--osd-playing-msg=Fukrey 3 (2023)  |  Fukrey 3 (2023) - HD Version [WEBDL-1080p][8bit][AVC][EAC3 5.1][HI]-TELLY[tmdbid-805785].mkv', '--start=0', '--input-ipc-server=\\\\.\\pipe\\pipe_nameA', '--script-opts-append=autoload-disabled=yes', '--fullscreen=yes']
...[12/21/23 08:06:49] mpv exit, return stop sec
127.0.0.1 - - [21/Dec/2023 08:07:03] "POST /embyToLocalPlayer/ HTTP/1.1" 200 -
[12/21/23 08:07:03] server=emby mount_disk_mode=False
[12/21/23 08:07:03] ['emby.xd_mix_host_ not match: gui[except_host] []']
[12/21/23 08:07:03] command line: ['C:\\Users\\_hide_user_\\Downloads\\mpv-x86_64-20231210-git-443c248\\mpv.exe', 'https://emby.xd_mix_host_/emby/videos/373/original.mkv?DeviceId=a4e7280e-6df0-4a47-867d-9a725e3da5cf&MediaSourceId=7eeeadab38ea5b51f46fa5353f5ade31&PlaySessionId=6295c5fd01054a2daa680bddd83558a2&api_key=_hide_api_key_&Static=true']
[12/21/23 08:07:03] ["emby.xd_mix_host_ match: playlist[enable_host] ['localhost', '127.0.0.1', '192.168.', '192-168-', 'example.com:8096', '.']"]
[12/21/23 08:07:03] ['C:\\Users\\_hide_user_\\Downloads\\mpv-x86_64-20231210-git-443c248\\mpv.exe', 'https://emby.xd_mix_host_/emby/videos/373/original.mkv?DeviceId=a4e7280e-6df0-4a47-867d-9a725e3da5cf&MediaSourceId=7eeeadab38ea5b51f46fa5353f5ade31&PlaySessionId=6295c5fd01054a2daa680bddd83558a2&api_key=_hide_api_key_&Static=true', '--force-media-title=Fukrey 3 (2023)  |  Fukrey 3 (2023) - HD Version [WEBDL-1080p][8bit][AVC][EAC3 5.1][HI]-TELLY[tmdbid-805785].mkv', '--osd-playing-msg=Fukrey 3 (2023)  |  Fukrey 3 (2023) - HD Version [WEBDL-1080p][8bit][AVC][EAC3 5.1][HI]-TELLY[tmdbid-805785].mkv', '--start=0', '--input-ipc-server=\\\\.\\pipe\\pipe_nameB', '--script-opts-append=autoload-disabled=yes', '--fullscreen=yes']
...[12/21/23 08:07:05] mpv exit, return stop sec
```

**Comment by kjtsune** [comment]
`mpv.conf > log-file = <save path>`

It might be a decoding issue; you can test with software decoding.
Check the mpv logs.

**Comment by xd003** [comment]
I don't know what really caused it earlier but i just added to startup and rebooted, mpv seems to be working fine now. Thanks for making this tool, its really good, until now i had to use Kodi which was heavy & slow

Just one last question, is it possible to start mpv process in background on start-up so that it opens very quickly when i click on play button ?

**Comment by kjtsune** [comment]
mpv is already quite fast; the waiting time depends on the connection speed between you and the Emby server.

**Comment by xd003** [comment]
Noted. its quite good already, 2-3 seconds waiting time. I am closing this issue
