### ISSUE TITLE
播放 plex 的时候 tools.py 报错

### ISSUE THREAD

**Issue by raylanb** [kjtsune/embyToLocalPlayer#31]
log.txt

```log
Exception occurred during processing of request from ('127.0.0.1', 61666)
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 318, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 349, in process_request
    self.finish_request(request, client_address)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 761, in __init__
    self.handle()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 436, in handle
    self.handle_one_request()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 424, in handle_one_request
    method()
  File "D:\Program Files\embyToLocalPlayer\embyToLocalPlayer.py", line 32, in do_POST
    data = parse_received_data_emby(data) if self.path.startswith('/emby') else parse_received_data_plex(data)
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\embyToLocalPlayer\utils\tools.py", line 448, in parse_received_data_plex
    provider_ids = [tuple(i['id'].split('://')) for i in meta['Guid']]
                                                         ~~~~^^^^^^^^
KeyError: 'Guid'
```

当删除以下代码之后可以正常播放 plex 视频。potplayer 可以回传进度，mpv 不行，mpvn 可以。

mpv 使用的是 https://github.com/dyphire/mpv-config

```python
provider_ids = [tuple(i['id'].split('://')) for i in meta['Guid']]
provider_ids = {k.title(): v for (k, v) in provider_ids}
trakt_emby_ver_dict = dict(
    Type=meta['type'],
    ProviderIds=provider_ids
)


res.update(trakt_emby_ver_dict)
```

**Comment by raylanb** [comment]
mpv将管道改为了

```python
cmd_pipe = fr'\\.\pipe\mpvsocket'
```

这样修改之后依然出现：

```log
[01/30/24 17:02:37] Cannot connect to pipe. init_player: init_times=4
[01/30/24 17:02:43] Cannot connect to pipe. init_player: init_times=5
[01/30/24 17:02:43] mpv not found skip playlist_add_mpv
[01/30/24 17:02:43] mpv not found, skip stop_sec_mpv
[01/30/24 17:02:43] skip update progress: playlist_data not found

```

**Comment by kjtsune** [comment]
KeyError: 'Guid'，因为没有刮削，修了。

**Comment by kjtsune** [comment]
这边若想固定管道名：
https://github.com/kjtsune/embyToLocalPlayer/blob/d47053b75a8d6dc7b397203b01215b3dad1f8d37/utils/players.py#L195
`pipe_name = 'mpvsocket'`
固定管道名后无法多开播放器。

**Comment by raylanb** [comment]
> 这边若想固定管道名：
> 
> https://github.com/kjtsune/embyToLocalPlayer/blob/d47053b75a8d6dc7b397203b01215b3dad1f8d37/utils/players.py#L195
> 
> 
> `pipe_name = 'mpvsocket'`
> 固定管道名后无法多开播放器。

即使这样固定过后，依然无法回传信息。已切换到potplayer播放，完美。
