### ISSUE TITLE
202403版本mpv，播放列表报错

### ISSUE THREAD

**Issue by verygoodlee** [kjtsune/embyToLocalPlayer#35]
Emby 4..8.3.0
mpv https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20240301

关键报错信息
```
Exception in thread Thread-14 (start_play):
Traceback (most recent call last):
  File "threading.py", line 1073, in _bootstrap_inner
  File "threading.py", line 1010, in run
  File "C:\Program Files\EmbyToLocalPlayer\embyToLocalPlayer.py", line 103, in start_play
    player_manager.playlist_add(eps_data=eps_data)
  File "C:\Program Files\EmbyToLocalPlayer\utils\players.py", line 60, in playlist_add
    self.playlist_data = playlist_fun[self.player_name](data=self.data, eps_data=eps_data, **self.player_kwargs)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\EmbyToLocalPlayer\utils\players.py", line 307, in playlist_add_mpv
    mpv.command(
  File "C:\Program Files\EmbyToLocalPlayer\utils\python_mpv_jsonipc.py", line 627, in command
    return self.mpv_inter.command(command, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\EmbyToLocalPlayer\utils\python_mpv_jsonipc.py", line 338, in command
    raise MPVError(data["error"])
utils.python_mpv_jsonipc.MPVError: invalid parameter
```

**Comment by verygoodlee** [comment]
我在这里加了一下打印`command`和`*args`
https://github.com/kjtsune/embyToLocalPlayer/blob/b71f2ea3905305e411954b5c1b84fd435dc2c876/utils/python_mpv_jsonipc.py#L305
```python
    def command(self, command, *args):
        print(f'command: {command}')
        print('args: ')
        for arg in args:
            print(arg)
```
看参数没发现啥问题
```
command: loadfile
args:
http://localhost:8096/emby/videos/11116/stream.mp4?DeviceId=0b81f2c3-f7e1-4a24-8c57-3e8325f12e93&MediaSourceId=c3f02a4cf2ed6e2095af3048a1f82846&PlaySessionId=de8e5019fc064a93ae1cbd85c33715b2&api_key=9ba4865c71db4db0a76d6ac52b316687&Static=true
append
title="繁花 S1:E2 - 阿宝被人栽赃陷害  |  S01E02.mp4",force-media-title="繁花 S1:E2 - 阿宝被人栽赃陷害  |  S01E02.mp4",osd-playing-msg="繁花 S1:E2 - 阿宝被人栽赃陷害  |  S01E02.mp4",start=0
```

**Comment by verygoodlee** [comment]
找到原因了，新版的loadfile命令改动了，多加了个参数
![image](https://github.com/kjtsune/embyToLocalPlayer/assets/45035465/baab15a5-586d-4cd8-a5f4-2501282e4a3a)

旧版是`loadfile <url> [<flags> [<options>]]`，新版是` loadfile <url> [<flags> [<index> [<options>]]]`，
上周刚改的 mpv-player/mpv@c678033
`index`参数是为新出的几个`insert-`模式准备的，`append`模式随便填个`-1`就行，
但是直接加会导致旧版mpv出问题，暂时先别动吧，这个commit下面已经有人反映不兼容旧语法了，可能后期还会变

**Comment by kjtsune** [comment]
issue貌似自动关闭，再开着放段时间看看吧，不过感觉 mpv 是不会改回来了。
