### ISSUE TITLE
Jellyfin更新到10.9.7版本后无法调用potplayer播放了求大佬救救

### ISSUE THREAD

**Issue by pitayala** [kjtsune/embyToLocalPlayer#57]

**Comment by pitayala** [comment]
![b4d3f547a89a951dc9999b8c56bab77](https://github.com/kjtsune/embyToLocalPlayer/assets/126130441/ed27fc4e-136d-4c9f-97b6-3489f9092464)
点击播放这个报错一闪而逝

**Comment by pitayala** [comment]
重新部署插件运行embyToLocalPlayer_debug.bat，报错：Traceback (most recent call last):
  File "D:\PotPlayer\tools\emby\embyToLocalPlayer.py", line 10, in <module>
    from utils.downloader import prefetch_resume_tv
ModuleNotFoundError: No module named 'utils'
all tasks are finished.

**Comment by pitayala** [comment]
报错
Traceback (most recent call last):
  File "threading.py", line 980, in _bootstrap_inner
  File "threading.py", line 917, in run
  File "D:\PotPlayer\tools\etlp-python-embed-win32\utils\http_server.py", line 217, in start_play
    cmd = get_player_cmd(media_path=data['media_path'], file_path=file_path)
  File "D:\PotPlayer\tools\etlp-python-embed-win32\utils\tools.py", line 226, in get_player_cmd
    raise FileNotFoundError(f'{media_path}\nmay need to disable read disk mode, '
FileNotFoundError: /volume3/番剧/S1/S01E24.mp4
may need to disable read disk mode, or enable path_check, see detail in FAQ

**Comment by kjtsune** [comment]
看FAQ
